### ISSUE TITLE
Lambda support for NodeJS 16 will in june 2024 

### ISSUE THREAD

**Issue by nico-is-coding** [mbonig/nightynight#162]
Please bump the NodeJS version.

Notes from AWS: "... We are ending support for Node.js 16 in Lambda on June 12, 2024. This follows Node.js 16 End-Of-Life (EOL) reached on September 11, 2023 ..."

**Comment by mbonig** [comment]
Thanks for the heads up. I've updated the code.

**Comment by nico-is-coding** [comment]
This was quick! Thanks!
